name: reczt_rich_share
description: App-local iOS rich-link QuickShare plugin for Reczt.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: RecztRichSharePlugin
